# Generated by RAG SYSTEM ADMIN v4.088
import time
import streamlit as st

st.set_page_config(page_title="건설사고-재발방지대책-RAG", page_icon='🔎', layout='wide')
st.title("건설사고-재발방지대책-RAG")
st.caption('Notebook에서 단계별로 작성한 RAG Streamlit 웹앱입니다.')

@st.cache_resource
def get_engine():
    import rag_engine
    return rag_engine

engine = get_engine()

if 'messages' not in st.session_state:
    st.session_state.messages = []

with st.sidebar:
    st.header('RAG 실행 정보')
    st.write('Top-K:', getattr(engine, 'RETRIEVAL_TOP_K', 3))
    st.write('신뢰성 검사:', 'ON' if getattr(engine, 'RELIABILITY_GUARD_ENABLED', False) else 'OFF')
    st.write('LLM 관련성 검사:', 'ON' if getattr(engine, 'LLM_RELEVANCE_CHECK_ENABLED', False) else 'OFF')
    st.write('출처 표시:', 'ON')
    st.write('Metadata 표시:', 'ON')
    st.write('처리시간 표시:', 'ON')
    if st.button('대화 초기화'):
        st.session_state.messages = []
        st.rerun()

for msg in st.session_state.messages:
    with st.chat_message(msg['role']):
        st.markdown(msg['content'])

prompt = st.chat_input('RAG 문서에 질문하세요')
if prompt:
    st.session_state.messages.append({'role':'user','content':prompt})
    with st.chat_message('user'):
        st.markdown(prompt)
    with st.chat_message('assistant'):
        started = time.perf_counter()
        with st.spinner('RAG 검색 및 답변 생성 중...'):
            try:
                answer = engine.answer(prompt, k=getattr(engine, 'RETRIEVAL_TOP_K', 3))
            except Exception as exc:
                answer = f'실행 오류: {type(exc).__name__}: {exc}'
        st.markdown(answer)
        st.caption(f'처리시간: {time.perf_counter()-started:.2f}초')
    st.session_state.messages.append({'role':'assistant','content':answer})
